use practice;
-- finding the max values
select max(discounted_price) from data ;
select max(marked_price) from data;
select max(discounted_price), max(marked_price) from data ;

-- finding the min values
select min(discounted_price) from data;
select min(marked_price) from data;
select min(discounted_price) ,min(marked_price)  from data;

-- finding the average values
select avg(discounted_price) from data;
select avg(marked_price) from data;
select avg(discounted_price) , avg(marked_price) from data;

-- finding the average value of brand puma
select avg(discounted_price) from data where brand_tag ='puma';
select max(discounted_price) from data where brand_tag ='puma';
select min(discounted_price) from data where brand_tag ='puma';


-- same command in one line
select avg(discounted_price), max(discounted_price) , min(discounted_price) from data where brand_tag ='puma';


-- same command with alliace
select avg(discounted_price) as 'avg', max(discounted_price) as 'max' , min(discounted_price) as 'min' from data where brand_tag ='puma';


-- Creating new columns of total revenue generated by each product
select product_name, discounted_price , rating, rating_count, (discounted_price * rating_count) as 'total revenue' from data;

-- Finding total revenue generated by all product
select sum(discounted_price * rating_count) as 'total revenue' from data;


-- Finding total products
select count(product_name) from data;

-- Finding number of products in Nike
select count(*) from data where brand_tag = 'nike';


-- Finding the name of categories nike serves
select distinct(product_tag) from data where brand_tag = 'nike';

-- Finding the number of categories nike serves
select count(distinct(product_tag)) from data where brand_tag = 'nike';


-- Finding the number of brands serves on myntra# round | Product with best rating | rating * rating count | ceil & floor
select count(brand_tag) from data;
select count(distinct(brand_tag)) from data;

select product_tag , rating * rating_count as 'rating_filter'from data;
select product_tag ,round((rating * rating_count),1) as 'rating_filter'from data;
 